import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {Providers} from "@/app/providers";
import {NavbarComponent} from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={"max-w-[1200px] mx-auto"}>
        <Providers>
            <NavbarComponent/>
            <main>
                {children}
            </main>
        </Providers>
      </body>
    </html>
  );
}
